/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorui;

/**
 *
 * @author karmo.tutk
 */
public class CalculatorUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorUI
     */
    public CalculatorUI() {
        initComponents();
    }

    /*
    * Puhastab pnlUp tekstialad.
     */
    private void clearMemory() {
        txtNumber.setText("");
        txtMemory.setText("");
        txtAction.setText("");
    }

    /* 
    * Puhastab ainult sisestatud numbri.
     */
    private void clearLastNumber() {
        txtNumber.setText("");
    }

    private void addNumber(String numberFromButton) {
        if (txtAction.getText().equals("=")) {
            clearMemory();
        }
        txtNumber.setText(txtNumber.getText() + numberFromButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        txtNumber = new javax.swing.JTextField();
        txtMemory = new javax.swing.JTextField();
        txtAction = new javax.swing.JTextField();
        pnlBottom = new javax.swing.JPanel();
        btnSeven = new javax.swing.JButton();
        btnEight = new javax.swing.JButton();
        btnFive = new javax.swing.JButton();
        btnTwo = new javax.swing.JButton();
        btnFour = new javax.swing.JButton();
        btnOne = new javax.swing.JButton();
        btnNine = new javax.swing.JButton();
        btnZero = new javax.swing.JButton();
        btnSix = new javax.swing.JButton();
        btnThree = new javax.swing.JButton();
        btnDot = new javax.swing.JButton();
        btnPlusMinus = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnDuplicate = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnX2 = new javax.swing.JButton();
        btnXY = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnC = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        btn1X = new javax.swing.JButton();
        btn10X = new javax.swing.JButton();
        btnPI = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulaator v2.0");

        pnlTop.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        txtNumber.setEditable(false);
        txtNumber.setBackground(new java.awt.Color(255, 255, 255));
        txtNumber.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        txtNumber.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtMemory.setEditable(false);
        txtMemory.setBackground(new java.awt.Color(255, 255, 255));
        txtMemory.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        txtAction.setEditable(false);
        txtAction.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtAction.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTopLayout = new javax.swing.GroupLayout(pnlTop);
        pnlTop.setLayout(pnlTopLayout);
        pnlTopLayout.setHorizontalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAction, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMemory, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                    .addComponent(txtNumber))
                .addContainerGap())
        );
        pnlTopLayout.setVerticalGroup(
            pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAction)
                    .addGroup(pnlTopLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtMemory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );

        pnlBottom.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

        btnSeven.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnSeven.setText("7");
        btnSeven.setMaximumSize(new java.awt.Dimension(70, 70));
        btnSeven.setMinimumSize(new java.awt.Dimension(70, 70));
        btnSeven.setPreferredSize(new java.awt.Dimension(70, 70));
        btnSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSevenActionPerformed(evt);
            }
        });

        btnEight.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnEight.setText("8");
        btnEight.setMaximumSize(new java.awt.Dimension(70, 70));
        btnEight.setMinimumSize(new java.awt.Dimension(70, 70));
        btnEight.setPreferredSize(new java.awt.Dimension(70, 70));
        btnEight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEightActionPerformed(evt);
            }
        });

        btnFive.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnFive.setText("5");
        btnFive.setMaximumSize(new java.awt.Dimension(70, 70));
        btnFive.setMinimumSize(new java.awt.Dimension(70, 70));
        btnFive.setPreferredSize(new java.awt.Dimension(70, 70));
        btnFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiveActionPerformed(evt);
            }
        });

        btnTwo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnTwo.setText("2");
        btnTwo.setMaximumSize(new java.awt.Dimension(70, 70));
        btnTwo.setMinimumSize(new java.awt.Dimension(70, 70));
        btnTwo.setPreferredSize(new java.awt.Dimension(70, 70));
        btnTwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwoActionPerformed(evt);
            }
        });

        btnFour.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnFour.setText("4");
        btnFour.setMaximumSize(new java.awt.Dimension(70, 70));
        btnFour.setMinimumSize(new java.awt.Dimension(70, 70));
        btnFour.setPreferredSize(new java.awt.Dimension(70, 70));
        btnFour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFourActionPerformed(evt);
            }
        });

        btnOne.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnOne.setText("1");
        btnOne.setMaximumSize(new java.awt.Dimension(70, 70));
        btnOne.setMinimumSize(new java.awt.Dimension(70, 70));
        btnOne.setPreferredSize(new java.awt.Dimension(70, 70));
        btnOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOneActionPerformed(evt);
            }
        });

        btnNine.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnNine.setText("9");
        btnNine.setMaximumSize(new java.awt.Dimension(70, 70));
        btnNine.setMinimumSize(new java.awt.Dimension(70, 70));
        btnNine.setPreferredSize(new java.awt.Dimension(70, 70));
        btnNine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNineActionPerformed(evt);
            }
        });

        btnZero.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnZero.setText("0");
        btnZero.setMaximumSize(new java.awt.Dimension(70, 70));
        btnZero.setMinimumSize(new java.awt.Dimension(70, 70));
        btnZero.setPreferredSize(new java.awt.Dimension(70, 70));
        btnZero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnZeroActionPerformed(evt);
            }
        });

        btnSix.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnSix.setText("6");
        btnSix.setMaximumSize(new java.awt.Dimension(70, 70));
        btnSix.setMinimumSize(new java.awt.Dimension(70, 70));
        btnSix.setPreferredSize(new java.awt.Dimension(70, 70));
        btnSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSixActionPerformed(evt);
            }
        });

        btnThree.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnThree.setText("3");
        btnThree.setMaximumSize(new java.awt.Dimension(70, 70));
        btnThree.setMinimumSize(new java.awt.Dimension(70, 70));
        btnThree.setPreferredSize(new java.awt.Dimension(70, 70));
        btnThree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThreeActionPerformed(evt);
            }
        });

        btnDot.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDot.setText(".");
        btnDot.setMaximumSize(new java.awt.Dimension(70, 70));
        btnDot.setMinimumSize(new java.awt.Dimension(70, 70));
        btnDot.setPreferredSize(new java.awt.Dimension(70, 70));
        btnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDotActionPerformed(evt);
            }
        });

        btnPlusMinus.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlusMinus.setText("±");
        btnPlusMinus.setMaximumSize(new java.awt.Dimension(70, 70));
        btnPlusMinus.setMinimumSize(new java.awt.Dimension(70, 70));
        btnPlusMinus.setPreferredSize(new java.awt.Dimension(70, 70));
        btnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusMinusActionPerformed(evt);
            }
        });

        btnPlus.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPlus.setText("+");
        btnPlus.setMaximumSize(new java.awt.Dimension(70, 70));
        btnPlus.setMinimumSize(new java.awt.Dimension(70, 70));
        btnPlus.setPreferredSize(new java.awt.Dimension(70, 70));
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMinus.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnMinus.setText("-");
        btnMinus.setMaximumSize(new java.awt.Dimension(70, 70));
        btnMinus.setMinimumSize(new java.awt.Dimension(70, 70));
        btnMinus.setPreferredSize(new java.awt.Dimension(70, 70));
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnDuplicate.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDuplicate.setText("*");
        btnDuplicate.setMaximumSize(new java.awt.Dimension(70, 70));
        btnDuplicate.setMinimumSize(new java.awt.Dimension(70, 70));
        btnDuplicate.setPreferredSize(new java.awt.Dimension(70, 70));
        btnDuplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuplicateActionPerformed(evt);
            }
        });

        btnDivide.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDivide.setText("/");
        btnDivide.setMaximumSize(new java.awt.Dimension(70, 70));
        btnDivide.setMinimumSize(new java.awt.Dimension(70, 70));
        btnDivide.setPreferredSize(new java.awt.Dimension(70, 70));
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnX2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnX2.setText("x²");
        btnX2.setMaximumSize(new java.awt.Dimension(70, 70));
        btnX2.setMinimumSize(new java.awt.Dimension(70, 70));
        btnX2.setPreferredSize(new java.awt.Dimension(70, 70));
        btnX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2ActionPerformed(evt);
            }
        });

        btnXY.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXY.setText("x^y");
        btnXY.setMaximumSize(new java.awt.Dimension(70, 70));
        btnXY.setMinimumSize(new java.awt.Dimension(70, 70));
        btnXY.setPreferredSize(new java.awt.Dimension(70, 70));
        btnXY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXYActionPerformed(evt);
            }
        });

        btnSqrt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSqrt.setText("sqrt");
        btnSqrt.setMaximumSize(new java.awt.Dimension(70, 70));
        btnSqrt.setMinimumSize(new java.awt.Dimension(70, 70));
        btnSqrt.setPreferredSize(new java.awt.Dimension(70, 70));
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });

        btnMod.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMod.setText("mod");
        btnMod.setMaximumSize(new java.awt.Dimension(70, 70));
        btnMod.setMinimumSize(new java.awt.Dimension(70, 70));
        btnMod.setPreferredSize(new java.awt.Dimension(70, 70));
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        btnCE.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCE.setText("CE");
        btnCE.setMaximumSize(new java.awt.Dimension(70, 70));
        btnCE.setMinimumSize(new java.awt.Dimension(70, 70));
        btnCE.setPreferredSize(new java.awt.Dimension(70, 70));
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btnC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnC.setText("C");
        btnC.setMaximumSize(new java.awt.Dimension(70, 70));
        btnC.setMinimumSize(new java.awt.Dimension(70, 70));
        btnC.setPreferredSize(new java.awt.Dimension(70, 70));
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        btnEnter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEnter.setText("=");
        btnEnter.setMaximumSize(new java.awt.Dimension(70, 70));
        btnEnter.setMinimumSize(new java.awt.Dimension(70, 70));
        btnEnter.setPreferredSize(new java.awt.Dimension(70, 70));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        btn1X.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn1X.setText("1/x");
        btn1X.setMaximumSize(new java.awt.Dimension(70, 70));
        btn1X.setMinimumSize(new java.awt.Dimension(70, 70));
        btn1X.setPreferredSize(new java.awt.Dimension(70, 70));
        btn1X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1XActionPerformed(evt);
            }
        });

        btn10X.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn10X.setText("10x");
        btn10X.setMaximumSize(new java.awt.Dimension(70, 70));
        btn10X.setMinimumSize(new java.awt.Dimension(70, 70));
        btn10X.setPreferredSize(new java.awt.Dimension(70, 70));
        btn10X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10XActionPerformed(evt);
            }
        });

        btnPI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPI.setText("PI");
        btnPI.setMaximumSize(new java.awt.Dimension(70, 70));
        btnPI.setMinimumSize(new java.awt.Dimension(70, 70));
        btnPI.setPreferredSize(new java.awt.Dimension(70, 70));
        btnPI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBottomLayout = new javax.swing.GroupLayout(pnlBottom);
        pnlBottom.setLayout(pnlBottomLayout);
        pnlBottomLayout.setHorizontalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBottomLayout.createSequentialGroup()
                        .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBottomLayout.createSequentialGroup()
                        .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBottomLayout.createSequentialGroup()
                                .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBottomLayout.createSequentialGroup()
                                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlBottomLayout.createSequentialGroup()
                                        .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlBottomLayout.createSequentialGroup()
                                        .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDuplicate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBottomLayout.createSequentialGroup()
                        .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBottomLayout.createSequentialGroup()
                        .addComponent(btnXY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn10X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBottomLayout.createSequentialGroup()
                        .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn1X, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(82, 82, 82)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBottomLayout.setVerticalGroup(
            pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBottomLayout.createSequentialGroup()
                        .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXY, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn10X, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPI, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBottomLayout.createSequentialGroup()
                        .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEight, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNine, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBottomLayout.createSequentialGroup()
                                .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDuplicate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlBottomLayout.createSequentialGroup()
                                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSix, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFour, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFive, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnThree, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnOne, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnDot, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnZero, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlBottomLayout.createSequentialGroup()
                            .addComponent(btnC, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(108, 108, 108))
                        .addComponent(btnEnter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn1X, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtActionActionPerformed

    private void btnNineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNineActionPerformed
        addNumber("9");
    }//GEN-LAST:event_btnNineActionPerformed

    private void btnZeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnZeroActionPerformed
        addNumber("0");
    }//GEN-LAST:event_btnZeroActionPerformed

    private void btnOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOneActionPerformed
        addNumber("1");
    }//GEN-LAST:event_btnOneActionPerformed

    private void btnTwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwoActionPerformed
        addNumber("2");
    }//GEN-LAST:event_btnTwoActionPerformed

    private void btnThreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThreeActionPerformed
        addNumber("3");
    }//GEN-LAST:event_btnThreeActionPerformed

    private void btnFourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFourActionPerformed
        addNumber("4");
    }//GEN-LAST:event_btnFourActionPerformed

    private void btnFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiveActionPerformed
        addNumber("5");
    }//GEN-LAST:event_btnFiveActionPerformed

    private void btnSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSixActionPerformed
        addNumber("6");
    }//GEN-LAST:event_btnSixActionPerformed

    private void btnSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSevenActionPerformed
        addNumber("7");
    }//GEN-LAST:event_btnSevenActionPerformed

    private void btnEightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEightActionPerformed
        addNumber("8");
    }//GEN-LAST:event_btnEightActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        clearLastNumber();
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        clearMemory();
    }//GEN-LAST:event_btnCActionPerformed

    private void btnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDotActionPerformed
        txtNumber.setText(txtNumber.getText() + ".");
        int countDot = 0;
        for (int i = 0; i < txtNumber.getText().length(); i++) {
            if (txtNumber.getText().substring(i, i + 1).equals(".")) {
                countDot++;
            }
        }
        if (countDot > 1) {
            txtNumber.setText(txtNumber.getText().substring(0, txtNumber.getText().length() - 1));
        }
    }//GEN-LAST:event_btnDotActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        addToMemory("+");
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusMinusActionPerformed
        String current = txtNumber.getText();
        if (current.length() > 0) {
            if (current.substring(0, 1).equals("-")) {
                txtNumber.setText(current.substring(1));
            } else {
                txtNumber.setText("-" + current);
            }
        } else {
            txtNumber.setText("-");
        }
    }//GEN-LAST:event_btnPlusMinusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        addToMemory("-");
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnDuplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuplicateActionPerformed
        addToMemory("*");
    }//GEN-LAST:event_btnDuplicateActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        addToMemory("/");
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        addToMemory("Mod");
    }//GEN-LAST:event_btnModActionPerformed

    private void btnXYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXYActionPerformed
        addToMemory("XY");
    }//GEN-LAST:event_btnXYActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        if (!txtMemory.getText().isEmpty() && !txtNumber.getText().isEmpty() && isFloat(txtNumber.getText())) {
            String op = txtAction.getText();
            txtAction.setText("=");
            float n1 = Float.parseFloat(txtMemory.getText());
            float n2 = Float.parseFloat(txtNumber.getText());
            if (!op.equals("/")) {
                switch (op) {
                    case "+":
                        txtNumber.setText(String.valueOf(n1 + n2));
                        break;
                    case "-":
                        txtNumber.setText(String.valueOf(n1 - n2));
                        break;
                    case "*":
                        txtNumber.setText(String.valueOf(n1 * n2));
                        break;
                    case "XY":
                        if (!Double.isInfinite(Math.pow(n1, n2))) {
                            txtNumber.setText(String.valueOf(Math.pow(n1, n2)));
                        } else {
                            txtNumber.setText("Liiga suur number");
                        }
                        break;
                    case "Mod":
                        txtNumber.setText(String.valueOf(n1 % n2));
                        break;

                }
            } else {
                if (n2 != 0) {
                    txtNumber.setText(String.valueOf(n1 / n2));
                } else {
                    txtNumber.setText("Jagamine nulliga");
                }

            }
            txtMemory.setText("");

        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2ActionPerformed
        if (!txtNumber.getText().isEmpty()) {
            float n1 = Float.parseFloat(txtNumber.getText());
            txtAction.setText("=");
            txtNumber.setText(String.valueOf(Math.pow(n1, 2)));
            }
    }//GEN-LAST:event_btnX2ActionPerformed

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
        if (!txtNumber.getText().isEmpty()) {
            float n1 = Float.parseFloat(txtNumber.getText());
            txtAction.setText("=");
            if (n1 >= 0) {
                txtNumber.setText(String.valueOf(Math.sqrt(n1)));
            } else {
                txtNumber.setText("Negatiivne arv!");
            }
        }
     }//GEN-LAST:event_btnSqrtActionPerformed

    private void btnPIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPIActionPerformed
        txtNumber.setText(String.valueOf(Math.PI));
    }//GEN-LAST:event_btnPIActionPerformed

    private void btn10XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10XActionPerformed
        if (!txtNumber.getText().isEmpty()) {
            float n1 = Float.parseFloat(txtNumber.getText());
            txtAction.setText("=");
            if (!Double.isInfinite(Math.pow(10, n1))) {
                txtNumber.setText(String.valueOf(Math.pow(10, n1)));
            } else {
                txtNumber.setText("Liiga suur number");
            }
        }
    }//GEN-LAST:event_btn10XActionPerformed

    private void btn1XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1XActionPerformed
        if (!txtNumber.getText().isEmpty()) {
            float n1 = Float.parseFloat(txtNumber.getText());
            txtAction.setText("=");
            if (!Double.isInfinite(1 / n1)) {
                txtNumber.setText(String.valueOf(1 / n1));
            } else {
                txtNumber.setText("Liiga suur number");
            }
        }
     }//GEN-LAST:event_btn1XActionPerformed

    /**
     * Kas on murdarv
     *
     * @param number
     * @return
     */
    private boolean isFloat(String number) {
        try {
            float tmp = Float.parseFloat(number);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    /**
     * Info lisatakse mällu
     *
     * @param operation märk stringina + - * / jne.
     */
    private void addToMemory(String operation) {
        if (isFloat(txtNumber.getText().trim())) {
            txtMemory.setText(txtNumber.getText());
            txtAction.setText(operation);
            clearLastNumber();
        } else {
            clearMemory();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn10X;
    private javax.swing.JButton btn1X;
    private javax.swing.JButton btnC;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnDot;
    private javax.swing.JButton btnDuplicate;
    private javax.swing.JButton btnEight;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnFive;
    private javax.swing.JButton btnFour;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnNine;
    private javax.swing.JButton btnOne;
    private javax.swing.JButton btnPI;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPlusMinus;
    private javax.swing.JButton btnSeven;
    private javax.swing.JButton btnSix;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnThree;
    private javax.swing.JButton btnTwo;
    private javax.swing.JButton btnX2;
    private javax.swing.JButton btnXY;
    private javax.swing.JButton btnZero;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTextField txtAction;
    private javax.swing.JTextField txtMemory;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables
}
